In [4]:
import numpy as np

# numPy matrix

In [20]:
# numPy matrix
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


- course test solution matrix

In [10]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


- count axis

In [12]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
b

15

- reshaping

In [13]:
a = np.ones((2,4))
b = a.reshape((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# data usage from local files

In [18]:
filedata = np.genfromtxt('data.txt', delimiter=',')
file = filedata[filedata < 50]

print(file)

[29. 32. 45. 15.  5. 22.]


- data sum

In [19]:
x = sum(file)
x

148.0